// 1과목: 데이터 모델링의 이해
export const SUBJECT1 = [
  {
    id: 101, category: '데이터모델링이해', subject: '1과목', type: '기출', difficulty: '하',
    question: '데이터 모델링의 3가지 요소로 올바른 것은?',
    options: ['엔터티, 속성, 관계', '테이블, 컬럼, 키', '개체, 튜플, 도메인', '스키마, 인스턴스, 뷰'],
    answer: 1,
    explanation: '데이터 모델링의 3요소는 엔터티(Entity), 속성(Attribute), 관계(Relationship)입니다.',
  },
  {
    id: 102, category: '데이터모델링이해', subject: '1과목', type: '기출', difficulty: '하',
    question: '데이터 모델링의 특징으로 옳지 않은 것은?',
    options: ['추상화', '단순화', '명확화', '복잡화'],
    answer: 4,
    explanation: '데이터 모델링의 특징: 추상화(현실 세계를 간략히 표현), 단순화(이해하기 쉽게), 명확화(누구나 동일하게 이해). 복잡화는 해당하지 않습니다.',
  },
  {
    id: 103, category: '데이터모델링이해', subject: '1과목', type: '기출', difficulty: '중',
    question: '데이터 모델링의 3단계 순서로 올바른 것은?',
    options: [
      '논리적 → 개념적 → 물리적',
      '개념적 → 논리적 → 물리적',
      '물리적 → 논리적 → 개념적',
      '개념적 → 물리적 → 논리적',
    ],
    answer: 2,
    explanation: '개념적 모델링(ERD 핵심 엔터티 도출) → 논리적 모델링(정규화, 속성 상세화) → 물리적 모델링(특정 DBMS에 맞는 테이블/인덱스 설계)',
  },
  {
    id: 104, category: '데이터모델링이해', subject: '1과목', type: '기출', difficulty: '하',
    question: '다음 중 개념적 데이터 모델링에 대한 설명으로 옳은 것은?',
    options: [
      '특정 DBMS의 물리적 구조를 고려하여 설계한다',
      '테이블과 컬럼을 상세하게 정의한다',
      '핵심 엔터티와 그 관계를 추상적으로 표현한다',
      '인덱스와 파티션을 정의한다',
    ],
    answer: 3,
    explanation: '개념적 모델링은 업무 중심의 포괄적인 수준에서 핵심 엔터티와 관계를 도출하는 단계로, 특정 DBMS에 종속되지 않습니다.',
  },
  {
    id: 105, category: '엔터티', subject: '1과목', type: '기출', difficulty: '하',
    question: '엔터티(Entity)의 특징으로 옳지 않은 것은?',
    options: [
      '반드시 속성을 가져야 한다',
      '유일한 식별자가 있어야 한다',
      '반드시 다른 엔터티와 관계를 가져야 한다',
      '업무에서 관리되어야 하는 집합이다',
    ],
    answer: 3,
    explanation: '엔터티가 반드시 다른 엔터티와 관계를 가져야 하는 것은 아닙니다. 독립적으로 존재하는 엔터티도 있습니다.',
  },
  {
    id: 106, category: '엔터티', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 엔터티의 분류로 옳지 않은 것은?',
    options: ['유형 엔터티', '개념 엔터티', '사건 엔터티', '관계 엔터티'],
    answer: 4,
    explanation: '엔터티는 유형(물리적 존재), 개념(논리적/개념적 존재), 사건(업무 수행 시 발생) 엔터티로 분류합니다. "관계 엔터티"는 공식 분류가 아닙니다.',
  },
  {
    id: 107, category: '엔터티', subject: '1과목', type: '변형', difficulty: '중',
    question: '다음 중 사건(Event) 엔터티의 예로 가장 적합한 것은?',
    options: ['직원', '부서', '주문', '제품'],
    answer: 3,
    explanation: '사건 엔터티는 업무를 수행함으로써 발생하는 엔터티입니다. 주문, 계약, 이벤트 등이 해당됩니다. 직원/부서/제품은 유형 엔터티입니다.',
  },
  {
    id: 108, category: '속성', subject: '1과목', type: '기출', difficulty: '하',
    question: '속성(Attribute)에 대한 설명으로 옳지 않은 것은?',
    options: [
      '엔터티가 가지는 세부적인 항목이다',
      '하나의 속성은 하나의 속성값을 가진다',
      '속성은 반드시 기본키가 되어야 한다',
      '업무에서 필요로 하는 항목이어야 한다',
    ],
    answer: 3,
    explanation: '속성이 반드시 기본키가 되어야 할 필요는 없습니다. 기본키는 식별자로 사용되는 특별한 속성이지만, 대부분의 속성은 일반 속성입니다.',
  },
  {
    id: 109, category: '속성', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 속성의 분류로 옳은 것은?',
    options: [
      '기본 속성, 설계 속성, 파생 속성',
      '주요 속성, 일반 속성, 외래 속성',
      '필수 속성, 선택 속성, 복합 속성',
      '단일 속성, 다중 속성, NULL 속성',
    ],
    answer: 1,
    explanation: '속성의 분류: 기본 속성(업무 분석에서 도출), 설계 속성(업무 규칙/설계 과정에서 도출), 파생 속성(다른 속성으로부터 계산/도출).',
  },
  {
    id: 110, category: '속성', subject: '1과목', type: '변형', difficulty: '중',
    question: '다음 중 파생 속성(Derived Attribute)의 예로 옳은 것은?',
    options: ['직원명', '주민등록번호', '나이(생년월일로부터 계산)', '부서코드'],
    answer: 3,
    explanation: '파생 속성은 다른 속성으로부터 계산/유도되는 속성입니다. 나이는 생년월일로부터 계산되므로 파생 속성입니다.',
  },
  {
    id: 111, category: '관계', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 관계(Relationship)에 대한 설명으로 옳지 않은 것은?',
    options: [
      '두 엔터티 사이의 업무적인 연관성이다',
      '관계는 반드시 양방향으로 정의되어야 한다',
      '관계의 카디널리티는 1:1, 1:N, M:N이 있다',
      '관계에 참여하는 방식은 필수/선택으로 나뉜다',
    ],
    answer: 2,
    explanation: '관계는 단방향으로 정의될 수도 있습니다. ERD에서 관계는 양방향 읽기가 가능하지만, 반드시 양방향으로 정의되어야 하는 것은 아닙니다.',
  },
  {
    id: 112, category: '관계', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 M:N 관계에 대한 설명으로 옳은 것은?',
    options: [
      'M:N 관계는 물리적 모델에서 그대로 구현 가능하다',
      'M:N 관계는 반드시 교차 엔터티(Intersection Entity)로 분리해야 한다',
      'M:N 관계는 존재할 수 없다',
      '관계형 데이터베이스에서 M:N 관계는 직접 표현 가능하다',
    ],
    answer: 2,
    explanation: 'M:N 관계는 관계형 DB에서 직접 구현할 수 없으므로, 중간에 교차 엔터티(Association Entity)를 생성하여 1:N + N:1 관계로 분리합니다.',
  },
  {
    id: 113, category: '식별자', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 주식별자(Primary Identifier)의 특징으로 옳지 않은 것은?',
    options: [
      '유일성: 엔터티 내 모든 인스턴스를 유일하게 구분할 수 있다',
      '최소성: 주식별자를 구성하는 속성의 수는 최소여야 한다',
      '불변성: 주식별자 값은 자주 변경되어도 무방하다',
      '존재성: 주식별자 값은 NULL이 될 수 없다',
    ],
    answer: 3,
    explanation: '주식별자는 불변성이 있어야 합니다. 식별자 값이 자주 변경되면 참조 무결성 등 많은 문제가 발생합니다.',
  },
  {
    id: 114, category: '식별자', subject: '1과목', type: '기출', difficulty: '중',
    question: '식별자 관계와 비식별자 관계에 대한 설명으로 옳은 것은?',
    options: [
      '식별자 관계에서 부모의 PK는 자식의 일반 속성(FK)이 된다',
      '비식별자 관계에서 부모의 PK는 자식의 PK에 포함된다',
      '식별자 관계는 실선, 비식별자 관계는 점선으로 표현한다',
      '비식별자 관계에서는 외래키가 생성되지 않는다',
    ],
    answer: 3,
    explanation: 'ERD 표기: 식별자 관계(실선) - 부모PK가 자식PK에 포함. 비식별자 관계(점선) - 부모PK가 자식의 일반 속성(FK)이 됨.',
  },
  {
    id: 115, category: '식별자', subject: '1과목', type: '변형', difficulty: '상',
    question: '다음 중 인조 식별자(Artificial Identifier) 사용이 적합한 경우는?',
    options: [
      '주식별자가 단순하고 불변할 때',
      '주식별자가 너무 복잡하거나 길 때',
      '주식별자 값이 자주 변경될 필요가 없을 때',
      '외부 시스템에서 식별자를 제공할 때',
    ],
    answer: 2,
    explanation: '인조 식별자(시퀀스, UUID 등)는 주식별자가 복잡하거나 길어서 조인 성능이 저하될 때, 또는 자연 식별자가 없거나 불안정할 때 사용합니다.',
  },
  {
    id: 116, category: '정규화', subject: '1과목', type: '기출', difficulty: '중',
    question: '제1정규형(1NF)의 조건으로 옳은 것은?',
    options: [
      '모든 속성이 기본키에 완전 함수 종속되어야 한다',
      '이행 함수 종속이 없어야 한다',
      '모든 속성의 도메인이 원자값(Atomic Value)이어야 한다',
      '모든 결정자가 후보키이어야 한다',
    ],
    answer: 3,
    explanation: '1NF: 릴레이션의 모든 속성 값이 원자값이어야 합니다. 반복 그룹이나 다중값 속성이 있으면 1NF를 위반합니다.',
  },
  {
    id: 117, category: '정규화', subject: '1과목', type: '기출', difficulty: '중',
    question: '제3정규형(3NF)의 조건으로 옳은 것은?',
    options: [
      '부분 함수 종속이 없어야 한다',
      '이행 함수 종속이 없어야 한다',
      '다치 종속이 없어야 한다',
      '조인 종속이 없어야 한다',
    ],
    answer: 2,
    explanation: '3NF: 2NF를 만족하면서, 이행 함수 종속(A→B→C 형태)을 제거해야 합니다. (A→C이면서 A→B, B→C인 경우)',
  },
  {
    id: 118, category: '정규화', subject: '1과목', type: '변형', difficulty: '상',
    question: 'BCNF(Boyce-Codd Normal Form)에 대한 설명으로 옳은 것은?',
    options: [
      '3NF보다 약한 정규형이다',
      '모든 결정자가 후보키이어야 한다',
      '다치 종속을 제거한 정규형이다',
      '조인 종속을 제거한 정규형이다',
    ],
    answer: 2,
    explanation: 'BCNF: 3NF보다 강한 정규형으로, X→Y가 성립할 때 X가 슈퍼키이어야 합니다. 즉 모든 결정자가 후보키이어야 합니다.',
  },
  {
    id: 119, category: '정규화', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 이상(Anomaly) 현상에 해당하지 않는 것은?',
    options: ['삽입 이상', '삭제 이상', '갱신 이상', '조회 이상'],
    answer: 4,
    explanation: '이상 현상은 삽입 이상(원하지 않는 데이터 삽입), 삭제 이상(원하지 않는 데이터 삭제), 갱신 이상(일부 튜플만 갱신)으로 구분됩니다. 조회 이상은 존재하지 않습니다.',
  },
  {
    id: 120, category: '반정규화', subject: '1과목', type: '기출', difficulty: '중',
    question: '반정규화(Denormalization)에 대한 설명으로 옳지 않은 것은?',
    options: [
      '데이터 무결성 유지가 어려워질 수 있다',
      '조회 성능 향상을 위해 수행한다',
      '데이터 중복이 발생한다',
      '정규화를 수행하기 전에 반드시 먼저 수행해야 한다',
    ],
    answer: 4,
    explanation: '반정규화는 정규화 이후에 성능 문제가 있을 때 수행합니다. 정규화 전에 반드시 수행해야 하는 것이 아닙니다.',
  },
  {
    id: 121, category: '반정규화', subject: '1과목', type: '변형', difficulty: '중',
    question: '다음 중 반정규화 기법에 해당하지 않는 것은?',
    options: ['테이블 병합', '컬럼 중복', '테이블 분할', '정규화 적용'],
    answer: 4,
    explanation: '반정규화 기법: 테이블 병합, 테이블 분할(수평/수직), 중복 컬럼 추가, 파생 컬럼 추가, 이력 테이블 추가 등. 정규화 적용은 반정규화의 반대입니다.',
  },
  {
    id: 122, category: '관계와조인', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 조인(Join)이 필요한 경우로 옳은 것은?',
    options: [
      '하나의 테이블에서 모든 데이터를 조회할 때',
      '여러 테이블에 분산된 데이터를 연결하여 조회할 때',
      '집계 함수를 사용할 때',
      '데이터를 정렬할 때',
    ],
    answer: 2,
    explanation: '조인은 정규화로 인해 여러 테이블에 분산된 데이터를 연결하여 하나의 결과로 가져올 때 필요합니다.',
  },
  {
    id: 123, category: '관계와조인', subject: '1과목', type: '변형', difficulty: '중',
    question: '다음 중 ERD(Entity Relationship Diagram) 표기법에 대한 설명으로 옳지 않은 것은?',
    options: [
      '엔터티는 직사각형으로 표현한다',
      '관계는 마름모로 표현한다(IE 표기법 기준)',
      'IE 표기법은 새발(Crow\'s Foot) 기호를 사용한다',
      'IDEF1X 표기법도 많이 사용된다',
    ],
    answer: 2,
    explanation: 'IE 표기법에서는 관계를 마름모가 아닌 선(Line)과 새발 기호(Crow\'s Foot)로 표현합니다. 마름모 표기는 Chen 표기법에서 사용합니다.',
  },
  {
    id: 124, category: '데이터모델링이해', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 데이터 독립성의 종류로 올바른 것은?',
    options: [
      '물리적 독립성, 논리적 독립성',
      '외부적 독립성, 내부적 독립성',
      '개념적 독립성, 실체적 독립성',
      '수평적 독립성, 수직적 독립성',
    ],
    answer: 1,
    explanation: '데이터 독립성: 논리적 독립성(논리 스키마 변경이 외부 스키마에 영향 없음), 물리적 독립성(물리 스키마 변경이 논리 스키마에 영향 없음).',
  },
  {
    id: 125, category: '데이터모델링이해', subject: '1과목', type: '기출', difficulty: '하',
    question: '3층 스키마(3-Schema Architecture)의 구성으로 옳은 것은?',
    options: [
      '외부 스키마, 개념 스키마, 내부 스키마',
      '논리 스키마, 물리 스키마, 뷰 스키마',
      '사용자 스키마, 관리자 스키마, 시스템 스키마',
      '입력 스키마, 처리 스키마, 출력 스키마',
    ],
    answer: 1,
    explanation: '3층 스키마: 외부 스키마(사용자 뷰), 개념 스키마(전체 논리 구조), 내부 스키마(물리적 저장 구조).',
  },
  {
    id: 126, category: '트랜잭션', subject: '1과목', type: '기출', difficulty: '중',
    question: '트랜잭션의 ACID 특성 중 "부분 완료가 없어야 한다"를 의미하는 것은?',
    options: ['원자성(Atomicity)', '일관성(Consistency)', '격리성(Isolation)', '지속성(Durability)'],
    answer: 1,
    explanation: '원자성(Atomicity): 트랜잭션의 모든 연산은 완전히 수행되거나 전혀 수행되지 않아야 합니다(All or Nothing).',
  },
  {
    id: 127, category: '트랜잭션', subject: '1과목', type: '변형', difficulty: '중',
    question: 'ACID 특성 중 "여러 트랜잭션이 동시에 실행될 때 서로 간섭하면 안 된다"를 의미하는 것은?',
    options: ['원자성(Atomicity)', '일관성(Consistency)', '격리성(Isolation)', '지속성(Durability)'],
    answer: 3,
    explanation: '격리성(Isolation): 트랜잭션이 실행되는 동안 다른 트랜잭션의 영향을 받지 않아야 합니다.',
  },
  {
    id: 128, category: '엔터티', subject: '1과목', type: '변형', difficulty: '중',
    question: '다음 중 독립 엔터티(Independent Entity)에 대한 설명으로 옳은 것은?',
    options: [
      '반드시 부모 엔터티가 있어야 존재할 수 있다',
      '다른 엔터티의 존재와 무관하게 독립적으로 존재할 수 있다',
      '항상 약한 엔터티(Weak Entity)와 같은 의미이다',
      '식별자가 없어도 된다',
    ],
    answer: 2,
    explanation: '독립 엔터티(강한 엔터티)는 자신의 식별자만으로 존재할 수 있으며 다른 엔터티에 의존하지 않습니다. 반대로 약한 엔터티는 부모 엔터티 없이 존재할 수 없습니다.',
  },
  {
    id: 129, category: '속성', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 복합 속성(Composite Attribute)의 예로 옳은 것은?',
    options: [
      '나이(생년월일로부터 계산)',
      '주소(시, 구, 동, 번지로 구성)',
      '직원번호',
      '부서명',
    ],
    answer: 2,
    explanation: '복합 속성은 여러 세부 속성으로 구성된 속성입니다. 주소는 시/구/동/번지 등의 세부 속성으로 분해할 수 있습니다.',
  },
  {
    id: 130, category: '관계', subject: '1과목', type: '기출', difficulty: '중',
    question: '관계의 페어링(Pairing)에 대한 설명으로 옳은 것은?',
    options: [
      '두 엔터티 사이의 관계를 정의하는 행위이다',
      '엔터티 인스턴스 사이의 논리적인 연관성이다',
      '관계의 카디널리티를 정의하는 것이다',
      '관계의 필수/선택 여부를 정의하는 것이다',
    ],
    answer: 2,
    explanation: '관계의 페어링(Pairing)은 엔터티 인스턴스(실제 데이터) 간의 연관성을 나타냅니다. 관계는 엔터티 타입 간의 관계이고, 페어링은 인스턴스 간 관계입니다.',
  },
  {
    id: 131, category: '정규화', subject: '1과목', type: '변형', difficulty: '상',
    question: '다음 중 함수 종속(Functional Dependency)에 대한 설명으로 옳은 것은?',
    options: [
      'A→B이면 B의 값으로 A의 값을 결정할 수 있다',
      'A→B이면 A의 값이 결정되면 B의 값이 유일하게 결정된다',
      'A→B, B→A이면 A와 B는 독립적이다',
      '함수 종속은 항상 1:1 대응을 의미한다',
    ],
    answer: 2,
    explanation: '함수 종속 A→B: A(결정자)의 값이 결정되면 B(종속자)의 값도 유일하게 결정됩니다. A가 B를 함수적으로 결정한다고 합니다.',
  },
  {
    id: 132, category: '반정규화', subject: '1과목', type: '변형', difficulty: '상',
    question: '다음 중 반정규화 수행 전 검토사항으로 옳지 않은 것은?',
    options: [
      '자주 사용하는 뷰(View)를 통해 해결 가능한지 검토한다',
      '클러스터링을 적용해 문제를 해결할 수 있는지 검토한다',
      '인덱스 추가로 성능 문제를 해결할 수 있는지 검토한다',
      '무조건 반정규화를 수행하여 성능을 향상시킨다',
    ],
    answer: 4,
    explanation: '반정규화는 성능 문제를 다른 방법(뷰, 인덱스, 클러스터링 등)으로 해결하지 못할 때 최후 수단으로 적용합니다. 무조건 적용하는 것은 올바르지 않습니다.',
  },
  {
    id: 133, category: '데이터모델링이해', subject: '1과목', type: '기출', difficulty: '하',
    question: '다음 중 관계형 데이터베이스(RDB)의 특징으로 옳지 않은 것은?',
    options: [
      '데이터를 2차원 테이블 형태로 저장한다',
      'SQL을 통해 데이터를 조작한다',
      '데이터 간의 관계를 포인터(Pointer)로 연결한다',
      '데이터 독립성을 지원한다',
    ],
    answer: 3,
    explanation: '관계형 DB는 포인터가 아닌 공통 컬럼(외래키)으로 테이블 간 관계를 표현합니다. 포인터로 연결하는 방식은 네트워크형/계층형 DB입니다.',
  },
  {
    id: 134, category: '식별자', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 후보키(Candidate Key)에 대한 설명으로 옳은 것은?',
    options: [
      '기본키로 선정된 키이다',
      '유일성과 최소성을 만족하는 키이다',
      '다른 테이블을 참조하는 키이다',
      'NULL 값을 허용하는 키이다',
    ],
    answer: 2,
    explanation: '후보키: 유일성(모든 튜플을 고유하게 식별)과 최소성(구성 속성 최소화)을 만족하는 키. 후보키 중 하나가 기본키로 선택됩니다.',
  },
  {
    id: 135, category: '식별자', subject: '1과목', type: '변형', difficulty: '중',
    question: '슈퍼키(Super Key)에 대한 설명으로 옳은 것은?',
    options: [
      '유일성과 최소성을 모두 만족하는 키이다',
      '유일성은 만족하지만 최소성은 만족하지 않을 수 있다',
      '최소성은 만족하지만 유일성은 만족하지 않을 수 있다',
      '항상 기본키와 동일하다',
    ],
    answer: 2,
    explanation: '슈퍼키: 유일성은 만족하지만 최소성은 만족하지 않아도 됩니다. 후보키는 슈퍼키 중 최소성도 만족하는 키입니다.',
  },
  {
    id: 136, category: '관계와조인', subject: '1과목', type: '변형', difficulty: '상',
    question: '다음 중 관계 차수(Degree)에 대한 설명으로 옳은 것은?',
    options: [
      '릴레이션에 저장된 튜플의 수이다',
      '릴레이션을 구성하는 속성의 수이다',
      '두 릴레이션 간의 카디널리티이다',
      '기본키를 구성하는 속성의 수이다',
    ],
    answer: 2,
    explanation: '차수(Degree): 릴레이션을 구성하는 속성(컬럼)의 수. 카디날리티(Cardinality): 릴레이션의 튜플(행)의 수.',
  },
  {
    id: 137, category: '데이터모델링이해', subject: '1과목', type: '기출', difficulty: '중',
    question: '도메인(Domain)에 대한 설명으로 옳은 것은?',
    options: [
      '속성이 가질 수 있는 값의 범위이다',
      '테이블의 행(Row)을 의미한다',
      '테이블 간의 관계를 정의한 것이다',
      '데이터베이스 내의 모든 테이블 목록이다',
    ],
    answer: 1,
    explanation: '도메인(Domain): 속성이 가질 수 있는 원자값들의 집합(범위). 예: 성별 도메인 = {\'M\', \'F\'}',
  },
  {
    id: 138, category: '정규화', subject: '1과목', type: '변형', difficulty: '상',
    question: '다음 중 4NF(제4정규형)의 조건으로 옳은 것은?',
    options: [
      '이행 함수 종속을 제거한다',
      '부분 함수 종속을 제거한다',
      '다치 종속(Multi-valued Dependency)을 제거한다',
      '조인 종속(Join Dependency)을 제거한다',
    ],
    answer: 3,
    explanation: '4NF: BCNF를 만족하면서 다치 종속이 없어야 합니다. 5NF는 조인 종속을 제거합니다.',
  },
  {
    id: 139, category: '엔터티', subject: '1과목', type: '변형', difficulty: '중',
    question: '다음 중 행위(Interaction) 엔터티에 해당하는 것은?',
    options: ['고객', '상품', '주문상세', '창고'],
    answer: 3,
    explanation: '행위 엔터티(교차 엔터티)는 두 엔터티 사이의 M:N 관계를 해소하기 위해 만들어진 엔터티입니다. 주문상세(주문+상품 관계)가 대표적 예입니다.',
  },
  {
    id: 140, category: '반정규화', subject: '1과목', type: '기출', difficulty: '중',
    question: '다음 중 수직 분할(Vertical Partitioning)에 대한 설명으로 옳은 것은?',
    options: [
      '테이블의 행(Row)을 기준으로 분리한다',
      '테이블의 컬럼(Column)을 기준으로 분리한다',
      '두 테이블을 하나로 합친다',
      '특정 컬럼을 다른 테이블에 중복 저장한다',
    ],
    answer: 2,
    explanation: '수직 분할: 자주 조회되는 컬럼과 잘 조회되지 않는 컬럼을 분리. 수평 분할: 특정 조건(기간, 지역 등)에 따라 행을 분리.',
  },
];
