// 2과목: SQL 기본 및 활용 (심화편 + 최적화)
export const SUBJECT2B = [
  {
    id: 301, category: '절차형SQL', subject: '2과목', type: '기출', difficulty: '상',
    question: '다음 중 PL/SQL의 구성요소로 옳지 않은 것은?',
    options: ['DECLARE(선언부)', 'BEGIN(실행부)', 'EXCEPTION(예외처리부)', 'COMMIT(확정부)'],
    answer: 4,
    explanation: 'PL/SQL 구조: DECLARE(변수/커서 선언), BEGIN(실행 로직), EXCEPTION(예외 처리), END. COMMIT은 별도의 TCL 문으로 PL/SQL 구성요소가 아닙니다.',
  },
  {
    id: 302, category: '절차형SQL', subject: '2과목', type: '기출', difficulty: '상',
    question: '저장 프로시저(Stored Procedure)에 대한 설명으로 옳지 않은 것은?',
    options: [
      '사전에 컴파일되어 데이터베이스에 저장된다',
      '반드시 값을 반환해야 한다',
      '입력/출력 매개변수를 가질 수 있다',
      '네트워크 트래픽을 줄일 수 있다',
    ],
    answer: 2,
    explanation: '저장 프로시저는 값을 반환하지 않아도 됩니다. 값을 반환하는 것은 함수(Function)입니다. 프로시저는 OUT 파라미터로 결과를 전달할 수 있습니다.',
  },
  {
    id: 303, category: '절차형SQL', subject: '2과목', type: '변형', difficulty: '상',
    question: '트리거(Trigger)에 대한 설명으로 옳지 않은 것은?',
    options: [
      'DML 이벤트(INSERT, UPDATE, DELETE) 발생 시 자동 실행된다',
      '사용자가 직접 호출하여 실행한다',
      'BEFORE/AFTER 시점을 지정할 수 있다',
      '데이터 무결성 강화에 활용된다',
    ],
    answer: 2,
    explanation: '트리거는 사용자가 직접 호출하는 것이 아니라 DML 이벤트가 발생할 때 자동으로 실행됩니다. 직접 호출은 프로시저나 함수의 특징입니다.',
  },
  {
    id: 304, category: '절차형SQL', subject: '2과목', type: '변형', difficulty: '상',
    question: '커서(Cursor)에 대한 설명으로 옳은 것은?',
    options: [
      'SQL 문장을 실행하기 위한 메모리 공간이다',
      'SELECT 결과 집합을 행 단위로 처리하기 위한 포인터이다',
      '데이터를 정렬하는 도구이다',
      '트랜잭션을 관리하는 객체이다',
    ],
    answer: 2,
    explanation: '커서(Cursor): 쿼리 결과 집합을 한 행씩 순차적으로 처리하기 위한 포인터/메커니즘입니다. 묵시적 커서(자동)와 명시적 커서(수동)로 나뉩니다.',
  },
  {
    id: 305, category: '옵티마이저', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 규칙 기반 옵티마이저(RBO)와 비용 기반 옵티마이저(CBO)에 대한 설명으로 옳은 것은?',
    options: [
      'RBO는 통계 정보를 활용하여 실행 계획을 수립한다',
      'CBO는 미리 정의된 우선순위 규칙에 따라 실행 계획을 수립한다',
      'CBO는 테이블 통계, 인덱스 통계 등을 이용하여 최적의 실행 계획을 수립한다',
      'RBO와 CBO는 동일한 방식으로 동작한다',
    ],
    answer: 3,
    explanation: 'CBO(Cost-Based Optimizer): 통계 정보(행 수, 분포도, 인덱스 구성 등)를 기반으로 예상 비용을 계산하여 최적 실행 계획 선택. RBO: 인덱스 유무, 연산자 종류 등 규칙 기반.',
  },
  {
    id: 306, category: '옵티마이저', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 옵티마이저 힌트(Hint)에 대한 설명으로 옳은 것은?',
    options: [
      '힌트는 항상 옵티마이저의 실행 계획을 강제로 변경한다',
      '힌트는 옵티마이저에게 특정 실행 계획을 제안하지만 무시될 수 있다',
      '힌트는 SQL 문법의 일부이다',
      '힌트를 사용하면 성능이 항상 향상된다',
    ],
    answer: 2,
    explanation: '힌트(Hint)는 /*+ HINT_NAME */ 형식으로 작성하며 옵티마이저에게 권고하는 것으로, 옵티마이저가 무시할 수 있습니다. 잘못된 힌트 사용은 오히려 성능 저하를 야기합니다.',
  },
  {
    id: 307, category: '인덱스', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 B-Tree 인덱스에 대한 설명으로 옳지 않은 것은?',
    options: [
      '범위 검색(BETWEEN, <, >)에 유리하다',
      '균형 잡힌 트리 구조로 검색 속도가 일정하다',
      '등가 검색(=)에만 사용할 수 있다',
      'NULL 값도 인덱스에 저장될 수 있다',
    ],
    answer: 3,
    explanation: 'B-Tree 인덱스는 등가 검색(=)뿐만 아니라 범위 검색(BETWEEN, <, >, LIKE \'A%\')도 지원합니다. 등가 검색만 지원하는 것은 Hash 인덱스입니다.',
  },
  {
    id: 308, category: '인덱스', subject: '2과목', type: '기출', difficulty: '상',
    question: '다음 중 인덱스 스캔 방식에 대한 설명으로 옳지 않은 것은?',
    options: [
      'Index Range Scan: 인덱스의 특정 범위를 스캔한다',
      'Index Full Scan: 인덱스 전체를 순차적으로 스캔한다',
      'Index Unique Scan: 유일한 단일 행을 검색한다',
      'Index Skip Scan: 인덱스의 선두 컬럼 조건이 있을 때만 사용 가능하다',
    ],
    answer: 4,
    explanation: 'Index Skip Scan: 선두 컬럼 조건이 없어도 사용 가능한 스캔 방식입니다. 선두 컬럼의 카디널리티가 낮을 때 효과적입니다.',
  },
  {
    id: 309, category: '조인수행원리', subject: '2과목', type: '기출', difficulty: '상',
    question: 'Nested Loop Join에 대한 설명으로 옳은 것은?',
    options: [
      '두 테이블을 정렬한 후 병합하는 방식이다',
      '해시 함수를 사용하여 조인하는 방식이다',
      '외부 테이블의 각 행에 대해 내부 테이블을 반복 스캔하는 방식이다',
      '항상 가장 빠른 조인 방식이다',
    ],
    answer: 3,
    explanation: 'Nested Loop Join: 외부(Driving) 테이블을 순차 스캔하면서 내부 테이블을 반복 조회. 소량 데이터나 인덱스가 있는 경우 유리. 대용량 테이블 간 조인에는 비효율적.',
  },
  {
    id: 310, category: '조인수행원리', subject: '2과목', type: '기출', difficulty: '상',
    question: 'Sort Merge Join에 대한 설명으로 옳은 것은?',
    options: [
      '조인 컬럼에 인덱스가 반드시 필요하다',
      '두 테이블을 조인 컬럼 기준으로 정렬한 후 순차적으로 병합한다',
      '항상 Hash Join보다 빠르다',
      '소량 데이터 처리에 최적화되어 있다',
    ],
    answer: 2,
    explanation: 'Sort Merge Join: 두 테이블을 조인 컬럼으로 정렬(Sort)한 뒤 순서대로 병합(Merge). 정렬 비용이 발생하며 인덱스 불필요. 대용량 데이터의 범위 조인에 적합.',
  },
  {
    id: 311, category: '조인수행원리', subject: '2과목', type: '변형', difficulty: '상',
    question: 'Hash Join에 대한 설명으로 옳지 않은 것은?',
    options: [
      '등가(=) 조인에서만 사용 가능하다',
      '해시 함수를 이용하여 조인 수행한다',
      '범위 조인(<, >)에도 사용 가능하다',
      '작은 테이블을 Build 테이블로 사용하면 효율적이다',
    ],
    answer: 3,
    explanation: 'Hash Join은 등가(=) 조인에서만 사용 가능합니다. 범위 조인(<, >)에는 Sort Merge Join이나 Nested Loop Join을 사용합니다.',
  },
  {
    id: 312, category: '실행계획', subject: '2과목', type: '기출', difficulty: '상',
    question: '실행 계획(Execution Plan) 확인 방법으로 옳은 것은?',
    options: [
      'SELECT PLAN FROM DUAL',
      'EXPLAIN PLAN FOR 또는 DBMS_XPLAN',
      'SHOW EXECUTION',
      'DESC PLAN',
    ],
    answer: 2,
    explanation: 'Oracle에서 실행 계획 확인: EXPLAIN PLAN FOR [SQL문] 실행 후 SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY) 또는 SQL 앞에 EXPLAIN 키워드 사용.',
  },
  {
    id: 313, category: '실행계획', subject: '2과목', type: '변형', difficulty: '상',
    question: '실행 계획에서 TABLE ACCESS FULL에 대한 설명으로 옳은 것은?',
    options: [
      '인덱스를 사용하여 테이블을 조회한다',
      '테이블 전체를 순차적으로 스캔한다',
      '특정 범위의 행만 스캔한다',
      '다른 테이블과 조인하여 조회한다',
    ],
    answer: 2,
    explanation: 'TABLE ACCESS FULL(Full Table Scan): 테이블의 모든 블록을 순차적으로 스캔합니다. 인덱스를 사용하지 않으며, 대량 데이터 조회 시 오히려 유리할 수 있습니다.',
  },
  {
    id: 314, category: '인덱스', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 인덱스를 타지 않는(무력화하는) 경우로 옳지 않은 것은?',
    options: [
      'WHERE COL LIKE \'%ABC\'',
      'WHERE COL IS NULL',
      'WHERE COL = 100',
      'WHERE TO_CHAR(COL) = \'100\'',
    ],
    answer: 3,
    explanation: 'WHERE COL = 100은 인덱스를 정상적으로 사용할 수 있습니다. LIKE \'%ABC\'(앞 %), IS NULL(단일 인덱스), TO_CHAR(COL)(함수 변환)은 인덱스를 무력화합니다.',
  },
  {
    id: 315, category: '옵티마이저', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 통계 정보 수집이 중요한 이유로 옳은 것은?',
    options: [
      'SQL 문법 오류를 방지한다',
      'CBO가 정확한 실행 계획을 수립하는 데 필요하다',
      '데이터 무결성을 보장한다',
      '트랜잭션 격리 수준을 결정한다',
    ],
    answer: 2,
    explanation: '비용 기반 옵티마이저(CBO)는 테이블/인덱스 통계 정보(행 수, 블록 수, 분포도 등)를 기반으로 실행 계획을 수립하므로, 최신 통계 정보 유지가 중요합니다.',
  },
  {
    id: 316, category: '윈도우함수', subject: '2과목', type: '기출', difficulty: '상',
    question: '다음 SQL에서 PERCENT_RANK()의 결과 범위로 옳은 것은?\n\nSELECT SAL,\n  PERCENT_RANK() OVER (ORDER BY SAL)\nFROM EMP;',
    options: ['0 이상 1 미만', '0 이상 1 이하', '1 이상 N 이하', '0 초과 100 이하'],
    answer: 2,
    explanation: 'PERCENT_RANK(): 첫 번째 행은 항상 0, 마지막 행은 항상 1. (순위-1)/(전체행수-1)로 계산. 범위는 0 이상 1 이하.',
  },
  {
    id: 317, category: '계층형질의', subject: '2과목', type: '변형', difficulty: '상',
    question: '계층형 질의에서 CONNECT BY NOCYCLE의 역할로 옳은 것은?',
    options: [
      '최상위 행만 조회한다',
      '순환 참조(무한 루프) 발생 시 오류 없이 처리한다',
      '계층의 최대 깊이를 제한한다',
      'NULL 값을 포함하지 않는다',
    ],
    answer: 2,
    explanation: 'CONNECT BY NOCYCLE: 데이터에 순환 참조(사이클)가 있을 때 무한 루프 없이 처리하도록 합니다. CYCLE 의사컬럼으로 순환 참조 여부를 확인할 수 있습니다.',
  },
  {
    id: 318, category: '서브쿼리', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 ANY 연산자에 대한 설명으로 옳은 것은?',
    options: [
      '서브쿼리 결과의 모든 값을 만족해야 한다',
      '서브쿼리 결과 중 하나라도 만족하면 된다',
      '서브쿼리가 결과를 반환하는지 확인한다',
      'NULL 값을 처리하는 연산자이다',
    ],
    answer: 2,
    explanation: '>ANY: 서브쿼리 결과 중 최솟값보다 크면 TRUE. =ANY는 IN과 동일. ALL: 서브쿼리 모든 값 만족 필요.',
  },
  {
    id: 319, category: '집합연산자', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL의 실행 결과로 옳은 것은?\n\nSELECT 1 AS NUM FROM DUAL\nUNION ALL\nSELECT 1 AS NUM FROM DUAL;',
    options: ['1행 반환', '2행 반환', '0행 반환', '오류'],
    answer: 2,
    explanation: 'UNION ALL은 중복 제거 없이 모든 행을 반환합니다. 동일한 값 1이 두 번 SELECT되므로 2행이 반환됩니다.',
  },
  {
    id: 320, category: '뷰', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 DML이 불가능한 뷰의 조건이 아닌 것은?',
    options: [
      'GROUP BY 절 사용',
      'DISTINCT 사용',
      'WHERE 절 사용',
      '집계 함수(SUM, COUNT 등) 사용',
    ],
    answer: 3,
    explanation: 'WHERE 절이 있는 단순 뷰는 DML이 가능합니다. GROUP BY, DISTINCT, 집계 함수, ROWNUM, 서브쿼리, 조인 등이 포함된 복잡한 뷰는 DML이 제한됩니다.',
  },
  {
    id: 321, category: '윈도우함수', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 윈도우 함수의 RANGE와 ROWS의 차이로 옳은 것은?',
    options: [
      'RANGE는 물리적 행 단위, ROWS는 논리적 값 범위 기준이다',
      'ROWS는 물리적 행 단위, RANGE는 논리적 값 범위 기준이다',
      'RANGE와 ROWS는 동일하게 동작한다',
      'ROWS는 정렬 없이 사용 가능하다',
    ],
    answer: 2,
    explanation: 'ROWS: 물리적 행 수 기준(현재 행 기준 위아래 N행). RANGE: 논리적 값 범위 기준(ORDER BY 컬럼 값이 같은 행은 동일하게 처리). 동점 처리 방식이 다름.',
  },
  {
    id: 322, category: 'SELECT/WHERE', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 ROWNUM에 대한 설명으로 옳지 않은 것은?',
    options: [
      'Oracle에서 결과 행에 순번을 부여하는 의사컬럼이다',
      'WHERE ROWNUM = 1은 첫 번째 행만 조회한다',
      'WHERE ROWNUM >= 2는 2번째 이후 행을 조회한다',
      'ORDER BY 이전에 ROWNUM이 부여된다',
    ],
    answer: 3,
    explanation: 'ROWNUM은 FROM 절 처리 후 WHERE 절 적용 시점에 부여되므로, WHERE ROWNUM >= 2는 항상 0건을 반환합니다. ROWNUM=1이 되어야 처음 행이 선택되고, 그 다음부터 2가 되기 때문입니다.',
  },
  {
    id: 323, category: '옵티마이저', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 SELECT 문에서 사용 가능한 옵티마이저 힌트의 예로 올바른 것은?',
    options: [
      '-- FULL(EMP)',
      '/* FULL(EMP) */',
      '/*+ FULL(EMP) */',
      '// FULL(EMP)',
    ],
    answer: 3,
    explanation: '옵티마이저 힌트 형식: SELECT /*+ 힌트명 */ ... 또는 SELECT --+ 힌트명 ... (한 줄 주석). /*+ */는 힌트 전용 주석으로 /*  */와는 다릅니다.',
  },
  {
    id: 324, category: '절차형SQL', subject: '2과목', type: '기출', difficulty: '상',
    question: '다음 중 사용자 정의 함수(User Defined Function)와 저장 프로시저의 차이로 옳은 것은?',
    options: [
      '함수는 반환값이 없고, 프로시저는 반환값이 있다',
      '함수는 반드시 하나의 값을 반환하고, SQL 문에 포함하여 사용 가능하다',
      '프로시저는 SQL 문 내에서 직접 사용 가능하다',
      '함수와 프로시저는 완전히 동일하다',
    ],
    answer: 2,
    explanation: '사용자 정의 함수: 반드시 단일 값 반환, SELECT 등 SQL문에서 직접 호출 가능. 저장 프로시저: 반환값 없거나 OUT 파라미터로 전달, EXECUTE/CALL로 실행.',
  },
  {
    id: 325, category: '인덱스', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 클러스터형 인덱스(Clustered Index)에 대한 설명으로 옳은 것은?',
    options: [
      '테이블에 여러 개 생성 가능하다',
      '데이터가 인덱스 순서대로 물리적으로 정렬되어 저장된다',
      '별도의 인덱스 세그먼트에 저장된다',
      'SELECT 성능에 영향을 주지 않는다',
    ],
    answer: 2,
    explanation: '클러스터형(Clustered) 인덱스: 테이블 데이터가 인덱스 키 순서대로 물리적으로 저장됨. 테이블당 1개만 가능. 비클러스터형(Non-clustered): 별도 인덱스 구조에 저장.',
  },
  {
    id: 326, category: '조인수행원리', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 Driving Table(선행 테이블) 선택 기준으로 옳은 것은?',
    options: [
      '데이터가 많은 테이블을 Driving Table로 선택한다',
      '데이터가 적거나 WHERE 조건으로 필터링 후 결과가 적은 테이블을 선택한다',
      '인덱스가 없는 테이블을 Driving Table로 선택한다',
      '항상 왼쪽 테이블이 Driving Table이 된다',
    ],
    answer: 2,
    explanation: 'Nested Loop Join에서 Driving Table은 결과 집합이 작을수록 좋습니다. 내부 테이블 반복 횟수를 줄이기 위해 WHERE 조건으로 필터링한 후 적은 행이 남는 테이블을 선행 테이블로 사용합니다.',
  },
  {
    id: 327, category: '실행계획', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 SQL 튜닝의 일반적인 순서로 올바른 것은?',
    options: [
      '인덱스 추가 → 실행 계획 분석 → SQL 재작성',
      '실행 계획 분석 → 문제점 파악 → SQL 재작성 또는 인덱스 조정',
      'SQL 재작성 → 실행 계획 분석 → 인덱스 추가',
      '문제점 파악 → 인덱스 삭제 → SQL 재작성',
    ],
    answer: 2,
    explanation: 'SQL 튜닝 순서: ① 실행 계획 확인 및 분석 → ② 성능 병목 파악 → ③ SQL 재작성/힌트/인덱스 조정 → ④ 결과 확인 및 반복',
  },
  {
    id: 328, category: '집합연산자', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 SQL에서 ORDER BY 사용 위치로 옳은 것은?\n\nSELECT COL1 FROM A\nUNION\nSELECT COL1 FROM B\n[여기에 ORDER BY?]',
    options: [
      '각 SELECT 문 뒤에 각각 사용해야 한다',
      '마지막 SELECT 문 뒤에 한 번만 사용해야 한다',
      '집합 연산자 중간에 사용해야 한다',
      '사용할 수 없다',
    ],
    answer: 2,
    explanation: '집합 연산자(UNION, INTERSECT, MINUS)를 사용할 때 ORDER BY는 전체 쿼리의 마지막에 한 번만 사용합니다. 각 SELECT에 ORDER BY를 사용하면 오류 발생.',
  },
  {
    id: 329, category: '계층형질의', subject: '2과목', type: '기출', difficulty: '상',
    question: 'START WITH 절에 대한 설명으로 옳은 것은?',
    options: [
      '계층 구조의 부모-자식 관계를 정의한다',
      '계층 탐색의 시작점(루트)을 지정한다',
      '계층의 최대 깊이를 제한한다',
      '순환 참조를 방지한다',
    ],
    answer: 2,
    explanation: 'START WITH: 계층 쿼리의 시작 행(루트)을 지정합니다. CONNECT BY PRIOR: 부모-자식 간 연결 방향을 정의합니다.',
  },
  {
    id: 330, category: 'DCL', subject: '2과목', type: '기출', difficulty: '중',
    question: 'REVOKE 문에 대한 설명으로 옳은 것은?\n\nREVOKE SELECT ON EMP FROM USER1;',
    options: [
      'USER1에게 EMP 테이블 SELECT 권한을 부여한다',
      'USER1의 EMP 테이블 SELECT 권한을 회수한다',
      'USER1이 다른 사용자에게 부여한 권한도 자동으로 회수된다',
      'USER1의 모든 권한을 회수한다',
    ],
    answer: 2,
    explanation: 'REVOKE 권한 ON 객체 FROM 사용자: 지정한 사용자로부터 권한을 회수합니다. CASCADE CONSTRAINTS 옵션을 사용해야 연쇄 회수가 가능합니다.',
  },
  {
    id: 331, category: '절차형SQL', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 PL/SQL에서 %ROWTYPE의 용도로 옳은 것은?',
    options: [
      '특정 컬럼의 데이터 타입을 참조한다',
      '테이블의 행 전체 구조를 변수에 적용한다',
      '커서의 결과 타입을 정의한다',
      '예외 처리에 사용되는 타입이다',
    ],
    answer: 2,
    explanation: '%ROWTYPE: 테이블이나 커서의 행 전체 컬럼 구조를 변수에 적용. %TYPE: 특정 컬럼의 데이터 타입 참조. 테이블 구조 변경 시 코드 수정 없이 자동 반영.',
  },
  {
    id: 332, category: '인덱스', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 함수 기반 인덱스(Function-Based Index)를 사용해야 하는 경우로 옳은 것은?',
    options: [
      'WHERE COL = 100',
      'WHERE COL BETWEEN 1 AND 100',
      'WHERE UPPER(COL) = \'SMITH\'',
      'WHERE COL LIKE \'A%\'',
    ],
    answer: 3,
    explanation: 'UPPER(COL)처럼 컬럼에 함수가 적용되면 일반 인덱스는 무력화됩니다. UPPER(COL)에 함수 기반 인덱스를 생성하면 WHERE UPPER(COL) = ... 조건에서 인덱스 활용이 가능합니다.',
  },
  {
    id: 333, category: '실행계획', subject: '2과목', type: '기출', difficulty: '상',
    question: '다음 중 SQL 성능 저하의 원인으로 옳지 않은 것은?',
    options: [
      '인덱스가 없는 컬럼에 조건 사용',
      '불필요한 DISTINCT 사용',
      '적절한 인덱스 사용',
      '대용량 테이블의 빈번한 Full Table Scan',
    ],
    answer: 3,
    explanation: '적절한 인덱스 사용은 성능 저하가 아닌 성능 향상의 원인입니다. 인덱스 미사용, 불필요한 DISTINCT/UNION, Full Table Scan이 성능 저하를 유발합니다.',
  },
  {
    id: 334, category: '조인수행원리', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 대용량 테이블 간 조인 시 가장 적합한 조인 방식은?',
    options: [
      'Nested Loop Join',
      'Hash Join 또는 Sort Merge Join',
      'Cross Join',
      '항상 Nested Loop Join이 가장 적합하다',
    ],
    answer: 2,
    explanation: '대용량 테이블 간 조인: Hash Join(메모리 기반, 등가조인)이나 Sort Merge Join(정렬 후 병합)이 적합합니다. Nested Loop Join은 소량 데이터나 인덱스가 있는 경우 유리합니다.',
  },
  {
    id: 335, category: '옵티마이저', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 바인드 변수(Bind Variable) 사용의 장점으로 옳은 것은?',
    options: [
      '항상 최적의 실행 계획을 수립한다',
      '동일한 실행 계획을 재사용하여 하드 파싱 비용을 줄인다',
      'NULL 처리가 자동으로 된다',
      '인덱스 사용이 보장된다',
    ],
    answer: 2,
    explanation: '바인드 변수 사용 시 SQL 텍스트가 동일하므로 동일한 실행 계획을 공유(소프트 파싱)할 수 있습니다. 리터럴 값 사용 시 매번 하드 파싱이 발생하여 성능 저하.',
  },
  {
    id: 336, category: 'SELECT/WHERE', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT DECODE(DEPTNO,\n  10, \'영업부\',\n  20, \'개발부\',\n  \'기타\')\nFROM EMP\nWHERE EMPNO = 1;',
    options: [
      'DEPTNO가 10이면 영업부, 20이면 개발부, 나머지는 기타를 반환한다',
      'DEPTNO가 10이고 20이면 각각 영업부, 개발부를 반환한다',
      'DEPTNO가 10 또는 20이 아니면 NULL을 반환한다',
      '항상 기타를 반환한다',
    ],
    answer: 1,
    explanation: 'DECODE(컬럼, 비교값1, 결과1, 비교값2, 결과2, 기본값): CASE WHEN과 유사. DEPTNO=10→영업부, 20→개발부, 그 외→기타.',
  },
  {
    id: 337, category: '계층형질의', subject: '2과목', type: '변형', difficulty: '상',
    question: '계층형 질의에서 SIBLINGS 키워드에 대한 설명으로 옳은 것은?\n\nORDER SIBLINGS BY SAL DESC',
    options: [
      '계층 전체를 SAL 기준으로 정렬한다',
      '같은 부모를 가진 형제 노드들을 SAL 기준으로 정렬한다',
      '형제 노드 간의 계층 관계를 정의한다',
      '최상위 노드만 SAL 기준으로 정렬한다',
    ],
    answer: 2,
    explanation: 'ORDER SIBLINGS BY: 계층 구조를 유지하면서 같은 부모를 가진 형제 노드들 사이에서만 정렬합니다. 일반 ORDER BY 사용 시 계층 구조가 깨질 수 있습니다.',
  },
  {
    id: 338, category: '서브쿼리', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 WITH 절(CTE: Common Table Expression)에 대한 설명으로 옳은 것은?',
    options: [
      '영구적으로 저장되는 뷰를 생성한다',
      '쿼리 내에서만 유효한 임시 결과 집합을 정의한다',
      '트랜잭션 내에서만 사용 가능하다',
      '인덱스를 자동으로 생성한다',
    ],
    answer: 2,
    explanation: 'WITH 절(CTE): WITH 절_이름 AS (서브쿼리) 형태로 쿼리 내에서만 사용 가능한 임시 결과 집합. 재귀적 CTE로 계층 데이터도 처리 가능. 뷰와 달리 저장되지 않음.',
  },
  {
    id: 339, category: '인덱스', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 인덱스 재구성(Rebuild)이 필요한 경우로 옳은 것은?',
    options: [
      'SELECT 쿼리가 자주 실행될 때',
      '인덱스 단편화(Fragmentation)가 심할 때',
      '새 컬럼을 추가할 때',
      '통계 정보를 수집할 때',
    ],
    answer: 2,
    explanation: '잦은 DML(INSERT/UPDATE/DELETE)로 인덱스 단편화가 발생하면 인덱스 효율이 저하됩니다. 이때 인덱스 재구성(REBUILD)을 통해 성능을 회복시킵니다.',
  },
  {
    id: 340, category: '옵티마이저', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 파티셔닝(Partitioning)에 대한 설명으로 옳지 않은 것은?',
    options: [
      '대용량 테이블을 논리적/물리적으로 분할한다',
      '파티션 프루닝(Pruning)으로 불필요한 파티션 스캔을 제거한다',
      '파티셔닝 후에는 인덱스가 필요 없다',
      '범위, 리스트, 해시 파티셔닝 등이 있다',
    ],
    answer: 3,
    explanation: '파티셔닝은 대용량 테이블 관리와 성능 향상에 도움을 주지만, 인덱스의 필요성을 없애지는 않습니다. 파티션 내에서도 인덱스가 필요할 수 있습니다.',
  },
  {
    id: 341, category: 'GROUP BY/HAVING', subject: '2과목', type: '변형', difficulty: '상',
    question: 'ROLLUP과 CUBE에 대한 설명으로 옳은 것은?\n\nGROUP BY ROLLUP(A, B)',
    options: [
      'ROLLUP: A, B 모든 조합의 소계/합계를 생성한다',
      'ROLLUP: 계층적으로 A별, A+B별 소계와 총계를 생성한다',
      'ROLLUP과 CUBE는 동일한 결과를 반환한다',
      'ROLLUP은 그룹별 평균만 계산한다',
    ],
    answer: 2,
    explanation: 'ROLLUP(A,B): (A,B)→(A)→()의 계층적 소계+총계 생성. CUBE(A,B): (A,B), (A), (B), ()의 모든 조합 소계+총계 생성.',
  },
  {
    id: 342, category: 'GROUP BY/HAVING', subject: '2과목', type: '기출', difficulty: '상',
    question: 'GROUPING SETS에 대한 설명으로 옳은 것은?\n\nGROUP BY GROUPING SETS(A, B)',
    options: [
      'A와 B를 동시에 그룹화한다',
      'A 기준 집계와 B 기준 집계를 UNION ALL한 것과 같다',
      'A와 B의 모든 조합을 집계한다',
      '총계만 계산한다',
    ],
    answer: 2,
    explanation: 'GROUPING SETS(A, B): A 기준 집계 결과와 B 기준 집계 결과를 UNION ALL한 것과 동일합니다. 원하는 그룹 조합만 선택적으로 집계할 수 있습니다.',
  },
  {
    id: 343, category: 'SELECT/WHERE', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL의 실행 결과로 옳은 것은?\n\nSELECT GREATEST(10, 20, 15) FROM DUAL;',
    options: ['10', '15', '20', '45'],
    answer: 3,
    explanation: 'GREATEST(값1, 값2, ...): 인자 중 가장 큰 값을 반환. LEAST()는 가장 작은 값 반환.',
  },
  {
    id: 344, category: '서브쿼리', subject: '2과목', type: '기출', difficulty: '상',
    question: '다음 중 서브쿼리에서 세미 조인(Semi Join)이 사용되는 경우로 옳은 것은?',
    options: [
      'IN이나 EXISTS 서브쿼리로 변환하여 최적화할 때',
      'CROSS JOIN을 수행할 때',
      'FULL OUTER JOIN을 수행할 때',
      '집계 함수를 서브쿼리에서 사용할 때',
    ],
    answer: 1,
    explanation: '세미 조인(Semi Join): IN/EXISTS 서브쿼리에서 옵티마이저가 내부적으로 적용하는 최적화 기법. 조인 결과가 메인 쿼리 기준으로 중복 없이 반환되도록 처리.',
  },
  {
    id: 345, category: '실행계획', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 SQL 수행 단계의 순서로 올바른 것은?',
    options: [
      '파싱 → 최적화 → 실행',
      '최적화 → 파싱 → 실행',
      '실행 → 파싱 → 최적화',
      '파싱 → 실행 → 최적화',
    ],
    answer: 1,
    explanation: 'SQL 수행 단계: ① 파싱(Parsing, 문법 검사/공유 풀 확인) → ② 최적화(Optimization, 실행 계획 수립) → ③ 실행(Execution, 데이터 처리)',
  },
];
