// 2과목: SQL 기본 및 활용 (기본편)
export const SUBJECT2A = [
  {
    id: 201, category: 'SELECT/WHERE', subject: '2과목', type: '기출', difficulty: '하',
    question: 'SELECT 문의 기본 구조로 옳은 것은?',
    options: [
      'SELECT 컬럼 FROM 테이블 WHERE 조건',
      'FROM 테이블 SELECT 컬럼 WHERE 조건',
      'SELECT 컬럼 WHERE 조건 FROM 테이블',
      'WHERE 조건 FROM 테이블 SELECT 컬럼',
    ],
    answer: 1,
    explanation: 'SELECT 문 기본 구조: SELECT [컬럼] FROM [테이블] WHERE [조건] GROUP BY [컬럼] HAVING [조건] ORDER BY [컬럼]',
  },
  {
    id: 202, category: 'SELECT/WHERE', subject: '2과목', type: '기출', difficulty: '하',
    question: 'DISTINCT 키워드에 대한 설명으로 옳은 것은?',
    options: [
      '결과를 정렬한다',
      '중복 행을 제거하여 결과를 반환한다',
      'NULL 값을 제거한다',
      '집계 함수와 함께 사용할 수 없다',
    ],
    answer: 2,
    explanation: 'DISTINCT는 SELECT 결과에서 중복된 행을 제거하여 고유한 행만 반환합니다.',
  },
  {
    id: 203, category: 'SELECT/WHERE', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 SQL의 실행 결과로 옳은 것은?\n\nSELECT *\nFROM EMP\nWHERE DEPTNO IN (10, 20)\n  AND SAL > 2000;',
    options: [
      'DEPTNO가 10 또는 20이거나 SAL이 2000 초과인 직원',
      'DEPTNO가 10 또는 20이면서 SAL이 2000 초과인 직원',
      'DEPTNO가 10이면서 SAL이 2000 초과이거나 DEPTNO가 20인 직원',
      'DEPTNO가 10이고 20이면서 SAL이 2000 초과인 직원',
    ],
    answer: 2,
    explanation: 'AND 연산자는 두 조건을 모두 만족해야 합니다. IN (10,20)은 DEPTNO=10 OR DEPTNO=20이며, AND SAL>2000 조건도 동시에 만족해야 합니다.',
  },
  {
    id: 204, category: 'SELECT/WHERE', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT ENAME\nFROM EMP\nWHERE ENAME LIKE \'%S%\';',
    options: [
      'ENAME이 S로 시작하는 직원',
      'ENAME이 S로 끝나는 직원',
      'ENAME에 S가 포함된 직원',
      'ENAME이 S인 직원',
    ],
    answer: 3,
    explanation: '\'%S%\': 앞뒤에 %가 있으므로 S가 어느 위치에 있든 포함된 문자열을 모두 검색합니다.',
  },
  {
    id: 205, category: 'SELECT/WHERE', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 WHERE 절에서 AND, OR, NOT의 우선순위로 옳은 것은?',
    options: [
      'OR > AND > NOT',
      'AND > OR > NOT',
      'NOT > AND > OR',
      'NOT > OR > AND',
    ],
    answer: 3,
    explanation: '연산자 우선순위: NOT > AND > OR. 괄호를 사용하면 우선순위를 변경할 수 있습니다.',
  },
  {
    id: 206, category: 'SELECT/WHERE', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 SQL에서 WHERE 조건을 만족하는 행은?\n\nWHERE COL1 = 1 OR COL2 = 2 AND COL3 = 3',
    options: [
      '(COL1=1 OR COL2=2) AND COL3=3 을 만족하는 행',
      'COL1=1 OR (COL2=2 AND COL3=3) 을 만족하는 행',
      'COL1=1 AND COL2=2 AND COL3=3 을 만족하는 행',
      '세 조건 중 하나라도 만족하는 행',
    ],
    answer: 2,
    explanation: 'AND가 OR보다 우선순위가 높으므로: COL1=1 OR (COL2=2 AND COL3=3)으로 처리됩니다.',
  },
  {
    id: 207, category: '함수', subject: '2과목', type: '기출', difficulty: '하',
    question: '다음 중 문자 함수로 옳지 않은 것은?',
    options: ['UPPER()', 'SUBSTR()', 'ROUND()', 'TRIM()'],
    answer: 3,
    explanation: 'ROUND()는 숫자 함수입니다. UPPER(대문자), SUBSTR(부분 문자열), TRIM(공백 제거)은 문자 함수입니다.',
  },
  {
    id: 208, category: '함수', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT ROUND(123.456, 1) FROM DUAL;',
    options: ['123', '123.4', '123.5', '124'],
    answer: 3,
    explanation: 'ROUND(숫자, 자릿수): 소수점 첫째 자리까지 반올림. 123.456에서 두 번째 소수 5를 반올림하면 123.5.',
  },
  {
    id: 209, category: '함수', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT TRUNC(123.789, 1) FROM DUAL;',
    options: ['123', '123.7', '123.8', '124'],
    answer: 2,
    explanation: 'TRUNC(숫자, 자릿수): 소수점 첫째 자리까지 절삭(반올림 없음). 123.789에서 소수점 이하 두 번째 자리부터 버리면 123.7.',
  },
  {
    id: 210, category: '함수', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 날짜 함수에 대한 설명으로 옳지 않은 것은?',
    options: [
      'SYSDATE는 현재 시스템의 날짜와 시간을 반환한다',
      'ADD_MONTHS(날짜, n)은 날짜에 n개월을 더한 날짜를 반환한다',
      'MONTHS_BETWEEN은 두 날짜 사이의 일수를 반환한다',
      'LAST_DAY는 해당 월의 마지막 날을 반환한다',
    ],
    answer: 3,
    explanation: 'MONTHS_BETWEEN(date1, date2)은 두 날짜 사이의 월 수를 반환합니다. 일수 차이는 날짜 빼기 연산(date1 - date2)으로 구합니다.',
  },
  {
    id: 211, category: '함수', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 중 TO_CHAR 함수의 설명으로 옳은 것은?',
    options: [
      '문자를 숫자로 변환한다',
      '날짜 또는 숫자를 문자로 변환한다',
      '문자를 날짜로 변환한다',
      '숫자를 날짜로 변환한다',
    ],
    answer: 2,
    explanation: 'TO_CHAR(값, 형식): 날짜나 숫자를 문자열로 변환. TO_NUMBER: 문자→숫자, TO_DATE: 문자→날짜.',
  },
  {
    id: 212, category: '함수', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT LENGTH(\'HELLO\') FROM DUAL;',
    options: ['4', '5', '6', '오류'],
    answer: 2,
    explanation: 'LENGTH(문자열)은 문자열의 길이를 반환합니다. \'HELLO\'는 5글자이므로 5를 반환합니다.',
  },
  {
    id: 213, category: '함수', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT SUBSTR(\'ABCDEF\', 2, 3)\nFROM DUAL;',
    options: ['ABC', 'BCD', 'CDE', 'BCDE'],
    answer: 2,
    explanation: 'SUBSTR(문자열, 시작위치, 길이): 2번째 위치부터 3글자 추출. B(2), C(3), D(4) → \'BCD\'',
  },
  {
    id: 214, category: '함수', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT LPAD(\'123\', 6, \'0\') FROM DUAL;',
    options: ['123000', '000123', '123   ', '   123'],
    answer: 2,
    explanation: 'LPAD(문자열, 전체길이, 채울문자): 전체 6자리가 되도록 왼쪽을 \'0\'으로 채웁니다. → \'000123\'',
  },
  {
    id: 215, category: 'NULL처리', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT NVL2(NULL, \'A\', \'B\') FROM DUAL;',
    options: ['NULL', 'A', 'B', '오류'],
    answer: 3,
    explanation: 'NVL2(expr, val_not_null, val_null): expr이 NULL이면 세 번째 인자, NULL이 아니면 두 번째 인자 반환. NULL이므로 \'B\' 반환.',
  },
  {
    id: 216, category: 'NULL처리', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT NULLIF(10, 10) FROM DUAL;',
    options: ['10', '0', 'NULL', '오류'],
    answer: 3,
    explanation: 'NULLIF(expr1, expr2): 두 값이 같으면 NULL, 다르면 첫 번째 값 반환. 10=10이므로 NULL 반환.',
  },
  {
    id: 217, category: 'NULL처리', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT 100 + NULL FROM DUAL;',
    options: ['100', '0', 'NULL', '오류'],
    answer: 3,
    explanation: 'NULL과의 산술 연산 결과는 항상 NULL입니다. 100 + NULL = NULL',
  },
  {
    id: 218, category: 'ORDER BY', subject: '2과목', type: '기출', difficulty: '하',
    question: 'ORDER BY 절에 대한 설명으로 옳지 않은 것은?',
    options: [
      'SELECT 문의 가장 마지막에 위치한다',
      'ASC는 오름차순(기본값), DESC는 내림차순이다',
      '여러 컬럼으로 정렬할 수 있다',
      'WHERE 절보다 먼저 실행된다',
    ],
    answer: 4,
    explanation: 'ORDER BY는 SQL 실행 순서에서 가장 마지막(SELECT 이후)에 실행됩니다. WHERE보다 나중에 실행됩니다.',
  },
  {
    id: 219, category: 'ORDER BY', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL에서 NULL 값을 가진 행의 정렬 위치는? (Oracle 기준)\n\nSELECT COL1 FROM T ORDER BY COL1 ASC;',
    options: ['맨 앞', '맨 뒤', '중간 임의 위치', 'NULL 행은 제외된다'],
    answer: 2,
    explanation: 'Oracle에서 ASC(오름차순) 정렬 시 NULL은 가장 마지막에 위치합니다. DESC(내림차순) 시에는 맨 앞에 위치합니다. (DBMS마다 다를 수 있음)',
  },
  {
    id: 220, category: 'GROUP BY/HAVING', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 집계 함수 중 NULL을 포함하여 계산하는 것은?',
    options: ['SUM()', 'AVG()', 'COUNT(*)', 'MAX()'],
    answer: 3,
    explanation: 'COUNT(*): 모든 행(NULL 포함) 카운트. COUNT(컬럼): NULL 제외. SUM, AVG, MAX, MIN: NULL 제외하고 계산.',
  },
  {
    id: 221, category: 'GROUP BY/HAVING', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 SQL의 결과로 옳은 것은?\n\n-- T: (1, NULL, 2, NULL, 3)\nSELECT AVG(COL1) FROM T;',
    options: ['1.2', '1.4', '2', 'NULL'],
    answer: 3,
    explanation: 'AVG()는 NULL을 제외하고 계산합니다. NULL이 아닌 값: 1, 2, 3 → AVG = (1+2+3)/3 = 2',
  },
  {
    id: 222, category: 'JOIN', subject: '2과목', type: '기출', difficulty: '중',
    question: 'EQUI JOIN(등가 조인)에 대한 설명으로 옳은 것은?',
    options: [
      '조인 조건에 = 이외의 연산자를 사용한다',
      '조인 조건에 = 연산자를 사용하여 두 테이블을 연결한다',
      '카테시안 곱을 반환한다',
      '자기 자신 테이블을 조인한다',
    ],
    answer: 2,
    explanation: 'EQUI JOIN: 두 테이블의 공통 컬럼을 = 연산자로 연결하는 가장 일반적인 조인 방식입니다.',
  },
  {
    id: 223, category: 'JOIN', subject: '2과목', type: '기출', difficulty: '중',
    question: 'NON-EQUI JOIN에 대한 설명으로 옳은 것은?',
    options: [
      '조인 조건에 = 연산자를 사용한다',
      '조인 조건에 BETWEEN, >, < 등 = 이외의 연산자를 사용한다',
      '두 테이블이 같은 구조를 가져야 한다',
      '항상 OUTER JOIN으로 처리된다',
    ],
    answer: 2,
    explanation: 'NON-EQUI JOIN: 등가(=) 조건이 아닌 BETWEEN, >, <, >=, <= 등의 연산자를 조인 조건으로 사용합니다.',
  },
  {
    id: 224, category: 'JOIN', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 SQL에서 오른쪽 테이블의 모든 행을 유지하면서 조인하려면?',
    options: [
      'LEFT OUTER JOIN',
      'RIGHT OUTER JOIN',
      'INNER JOIN',
      'CROSS JOIN',
    ],
    answer: 2,
    explanation: 'RIGHT OUTER JOIN: 오른쪽 테이블의 모든 행을 반환하고, 왼쪽 테이블에 매칭 행이 없으면 NULL로 채웁니다.',
  },
  {
    id: 225, category: 'JOIN', subject: '2과목', type: '기출', difficulty: '상',
    question: 'FULL OUTER JOIN에 대한 설명으로 옳은 것은?',
    options: [
      '두 테이블에서 조인 조건을 만족하는 행만 반환한다',
      '왼쪽 테이블의 모든 행을 반환한다',
      '두 테이블 모두의 모든 행을 반환하며, 매칭 없는 쪽은 NULL로 채운다',
      '두 테이블의 카테시안 곱을 반환한다',
    ],
    answer: 3,
    explanation: 'FULL OUTER JOIN: LEFT OUTER JOIN + RIGHT OUTER JOIN의 결합. 양쪽 테이블의 모든 행을 포함하고, 매칭되지 않는 쪽은 NULL로 표시됩니다.',
  },
  {
    id: 226, category: '서브쿼리', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 서브쿼리의 위치에 따른 분류로 옳지 않은 것은?',
    options: [
      'SELECT 절 서브쿼리: 스칼라 서브쿼리',
      'FROM 절 서브쿼리: 인라인 뷰(Inline View)',
      'WHERE 절 서브쿼리: 중첩 서브쿼리',
      'ORDER BY 절 서브쿼리: 정렬 서브쿼리',
    ],
    answer: 4,
    explanation: '서브쿼리는 SELECT, FROM, WHERE, HAVING 절에 사용할 수 있습니다. ORDER BY 절 서브쿼리는 일반적인 분류에 포함되지 않습니다.',
  },
  {
    id: 227, category: '서브쿼리', subject: '2과목', type: '변형', difficulty: '중',
    question: '인라인 뷰(Inline View)에 대한 설명으로 옳은 것은?',
    options: [
      'SELECT 절에 위치하는 서브쿼리이다',
      'FROM 절에 위치하며 가상 테이블처럼 사용된다',
      'WHERE 절에 위치하는 서브쿼리이다',
      '저장된 뷰(View)와 동일하다',
    ],
    answer: 2,
    explanation: '인라인 뷰: FROM 절에 위치하는 서브쿼리로, 실행 시 임시 가상 테이블처럼 동작합니다. 저장된 뷰와 달리 SQL 내에서만 존재합니다.',
  },
  {
    id: 228, category: '서브쿼리', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 중 단일행 서브쿼리(Single Row Subquery)에 사용 가능한 연산자가 아닌 것은?',
    options: ['=', '>', 'IN', '<='],
    answer: 3,
    explanation: 'IN은 다중행 서브쿼리(Multiple Row Subquery)에 사용합니다. 단일행 서브쿼리에는 =, >, <, >=, <=, <> 등의 비교 연산자를 사용합니다.',
  },
  {
    id: 229, category: 'DCL', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 DCL(Data Control Language)에 해당하는 것은?',
    options: ['SELECT', 'INSERT', 'GRANT', 'CREATE'],
    answer: 3,
    explanation: 'DCL: GRANT(권한 부여), REVOKE(권한 회수). SELECT/INSERT는 DML, CREATE는 DDL입니다.',
  },
  {
    id: 230, category: 'DCL', subject: '2과목', type: '변형', difficulty: '중',
    question: 'GRANT 문에 대한 설명으로 옳은 것은?\n\nGRANT SELECT ON EMP TO USER1;',
    options: [
      'USER1에게 EMP 테이블의 모든 권한을 부여한다',
      'USER1에게 EMP 테이블에 대한 SELECT 권한을 부여한다',
      'USER1의 EMP 테이블 SELECT 권한을 회수한다',
      'USER1이 EMP 테이블을 생성할 수 있게 한다',
    ],
    answer: 2,
    explanation: 'GRANT 권한 ON 객체 TO 사용자: 지정한 사용자에게 해당 객체에 대한 특정 권한을 부여합니다.',
  },
  {
    id: 231, category: 'DCL', subject: '2과목', type: '변형', difficulty: '중',
    question: 'WITH GRANT OPTION에 대한 설명으로 옳은 것은?',
    options: [
      '자동으로 모든 권한을 부여한다',
      '권한을 받은 사용자가 다른 사용자에게 동일 권한을 부여할 수 있다',
      '권한 부여를 취소한다',
      '권한을 영구적으로 저장한다',
    ],
    answer: 2,
    explanation: 'WITH GRANT OPTION: 권한을 받은 사용자가 그 권한을 다른 사용자에게 다시 부여(전파)할 수 있게 합니다.',
  },
  {
    id: 232, category: 'TCL', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 ROLLBACK에 대한 설명으로 옳지 않은 것은?',
    options: [
      '트랜잭션의 변경 내용을 취소한다',
      'COMMIT된 데이터도 ROLLBACK으로 취소할 수 있다',
      'SAVEPOINT를 이용해 부분 롤백이 가능하다',
      'DDL 문장 실행 후에는 이전 DML이 자동 COMMIT된다',
    ],
    answer: 2,
    explanation: 'COMMIT된 트랜잭션은 ROLLBACK으로 취소할 수 없습니다. ROLLBACK은 아직 COMMIT되지 않은 변경 내용만 취소합니다.',
  },
  {
    id: 233, category: 'DDL', subject: '2과목', type: '기출', difficulty: '중',
    question: 'CREATE TABLE 문에서 DEFAULT 값 설정에 대한 설명으로 옳은 것은?',
    options: [
      'INSERT 시 해당 컬럼에 값을 입력하지 않으면 DEFAULT 값이 삽입된다',
      'DEFAULT 값은 항상 숫자여야 한다',
      'DEFAULT 값이 있으면 NOT NULL 제약이 필요 없다',
      'DEFAULT 값은 NULL만 허용된다',
    ],
    answer: 1,
    explanation: 'DEFAULT: INSERT 시 해당 컬럼에 값을 명시하지 않거나 DEFAULT 키워드를 사용하면 지정된 기본값이 자동으로 삽입됩니다.',
  },
  {
    id: 234, category: 'DDL', subject: '2과목', type: '변형', difficulty: '중',
    question: 'ALTER TABLE에 대한 설명으로 옳지 않은 것은?',
    options: [
      'ADD: 새 컬럼 추가',
      'DROP COLUMN: 컬럼 삭제',
      'MODIFY: 컬럼의 데이터 타입/크기 변경',
      'TRUNCATE: 테이블의 모든 데이터 삭제',
    ],
    answer: 4,
    explanation: 'TRUNCATE는 ALTER TABLE의 하위 구문이 아닌 독립적인 DDL 문장입니다. ALTER TABLE은 ADD, DROP COLUMN, MODIFY, RENAME 등의 구문을 지원합니다.',
  },
  {
    id: 235, category: 'DDL', subject: '2과목', type: '기출', difficulty: '중',
    question: 'DROP TABLE과 TRUNCATE TABLE의 차이로 옳은 것은?',
    options: [
      'DROP은 데이터만 삭제하고 테이블 구조는 유지한다',
      'TRUNCATE는 테이블 구조까지 완전히 삭제한다',
      'DROP은 테이블 구조와 데이터를 모두 삭제한다',
      'TRUNCATE는 WHERE 조건으로 선택 삭제가 가능하다',
    ],
    answer: 3,
    explanation: 'DROP TABLE: 테이블 구조와 데이터를 모두 삭제(테이블 자체 제거). TRUNCATE TABLE: 데이터만 삭제하고 테이블 구조는 유지.',
  },
  {
    id: 236, category: 'DML', subject: '2과목', type: '기출', difficulty: '하',
    question: '다음 INSERT 문의 실행 결과로 옳은 것은?\n\nINSERT INTO EMP (EMPNO, ENAME)\nVALUES (1001, \'홍길동\');',
    options: [
      'EMP 테이블에 EMPNO=1001, ENAME=\'홍길동\'인 행이 추가된다',
      'EMP 테이블에서 EMPNO=1001인 행이 수정된다',
      'EMP 테이블에서 ENAME=\'홍길동\'인 행이 삭제된다',
      '오류가 발생한다',
    ],
    answer: 1,
    explanation: 'INSERT INTO 테이블(컬럼1, 컬럼2) VALUES(값1, 값2): 지정한 컬럼에 해당 값을 가진 새 행을 삽입합니다. 명시되지 않은 컬럼은 NULL 또는 DEFAULT 값이 입력됩니다.',
  },
  {
    id: 237, category: 'DML', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL의 실행 결과로 옳은 것은?\n\nDELETE FROM EMP\nWHERE DEPTNO = 30;',
    options: [
      'DEPTNO=30인 직원의 DEPTNO를 NULL로 변경한다',
      'DEPTNO=30인 직원 행을 모두 삭제한다',
      'DEPTNO=30인 부서를 삭제한다',
      'EMP 테이블의 모든 행을 삭제한다',
    ],
    answer: 2,
    explanation: 'DELETE FROM 테이블 WHERE 조건: 조건을 만족하는 행을 삭제합니다. WHERE를 생략하면 모든 행이 삭제됩니다.',
  },
  {
    id: 238, category: '집합연산자', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 MINUS(EXCEPT) 연산자에 대한 설명으로 옳은 것은?',
    options: [
      '두 쿼리의 합집합을 반환한다',
      '두 쿼리의 교집합을 반환한다',
      '첫 번째 쿼리 결과에서 두 번째 쿼리 결과를 뺀 차집합을 반환한다',
      '두 번째 쿼리 결과에서 첫 번째 쿼리 결과를 뺀 차집합을 반환한다',
    ],
    answer: 3,
    explanation: 'MINUS(Oracle) / EXCEPT(SQL Server/PostgreSQL): 첫 번째 쿼리 결과에서 두 번째 쿼리 결과와 겹치는 행을 제거한 차집합을 반환합니다.',
  },
  {
    id: 239, category: '계층형질의', subject: '2과목', type: '기출', difficulty: '상',
    question: 'Oracle의 계층형 질의에서 CONNECT BY PRIOR에 대한 설명으로 옳은 것은?',
    options: [
      '최상위 행을 지정한다',
      '계층 관계에서 부모-자식 간의 방향을 정의한다',
      '계층의 깊이를 제한한다',
      '계층의 정렬 방식을 결정한다',
    ],
    answer: 2,
    explanation: 'CONNECT BY PRIOR 자식컬럼 = 부모컬럼: 부모→자식 방향으로 조회(하향식). CONNECT BY PRIOR 부모컬럼 = 자식컬럼: 자식→부모 방향(상향식).',
  },
  {
    id: 240, category: '계층형질의', subject: '2과목', type: '변형', difficulty: '상',
    question: '계층형 질의에서 LEVEL 의사컬럼(Pseudocolumn)에 대한 설명으로 옳은 것은?',
    options: [
      '전체 행의 순번을 나타낸다',
      '계층 구조에서 현재 행의 깊이(레벨)를 나타낸다',
      '부모 행의 ROWID를 반환한다',
      '계층의 총 깊이를 반환한다',
    ],
    answer: 2,
    explanation: 'LEVEL: 계층형 질의에서 루트(최상위)는 1, 그 아래 자식은 2, 손자는 3으로 증가하는 깊이 값을 반환합니다.',
  },
  {
    id: 241, category: '뷰', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 뷰(View)를 사용하는 이유로 옳지 않은 것은?',
    options: [
      '보안 강화(민감한 컬럼 숨김)',
      '복잡한 쿼리의 단순화',
      '저장 공간 절약',
      '독립성 제공(기본 테이블 변경 시 영향 최소화)',
    ],
    answer: 3,
    explanation: '뷰는 실제 데이터를 저장하지 않으므로 저장 공간 절약과는 관련이 없습니다. 오히려 뷰 정의 자체를 저장하는 공간이 필요합니다.',
  },
  {
    id: 242, category: '윈도우함수', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 중 PARTITION BY와 GROUP BY의 차이로 옳은 것은?',
    options: [
      'PARTITION BY는 결과 행을 줄이지만 GROUP BY는 줄이지 않는다',
      'GROUP BY는 결과 행을 줄이지만 PARTITION BY는 줄이지 않는다',
      'PARTITION BY와 GROUP BY 모두 결과 행을 줄인다',
      'PARTITION BY와 GROUP BY 모두 결과 행을 줄이지 않는다',
    ],
    answer: 2,
    explanation: 'GROUP BY: 그룹별로 집약하여 행 수가 줄어듦. PARTITION BY(윈도우 함수): 그룹을 나누지만 각 행이 유지되어 원본 행 수와 동일.',
  },
  {
    id: 243, category: '윈도우함수', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 SQL의 결과로 CUME_DIST()가 반환하는 값의 범위로 옳은 것은?\n\nSELECT SAL, CUME_DIST() OVER (ORDER BY SAL) FROM EMP;',
    options: ['0 이상 1 미만', '0 초과 1 이하', '1 이상 N 이하', '음수~양수'],
    answer: 2,
    explanation: 'CUME_DIST(): 현재 행보다 작거나 같은 값의 비율(0 초과 1 이하). 0은 불가능하며(최소 1/N), 최대값은 1입니다.',
  },
  {
    id: 244, category: '윈도우함수', subject: '2과목', type: '기출', difficulty: '상',
    question: '다음 SQL에서 FIRST_VALUE()의 용도로 옳은 것은?\n\nSELECT ENAME, SAL,\n  FIRST_VALUE(SAL)\n    OVER (PARTITION BY DEPTNO\n          ORDER BY SAL) AS MIN_SAL\nFROM EMP;',
    options: [
      '부서별 전체 평균 급여를 반환한다',
      '부서 내에서 급여가 가장 낮은 직원의 급여를 반환한다',
      '부서 내 첫 번째로 입사한 직원의 급여를 반환한다',
      '전체에서 가장 낮은 급여를 반환한다',
    ],
    answer: 2,
    explanation: 'FIRST_VALUE(컬럼) OVER (PARTITION BY ... ORDER BY SAL): 파티션 내 ORDER BY 기준 첫 번째 값을 반환합니다. SAL 오름차순이므로 부서 내 최솟값.',
  },
  {
    id: 245, category: 'SELECT/WHERE', subject: '2과목', type: '기출', difficulty: '중',
    question: 'SELECT 절에서 alias(별칭) 사용에 대한 설명으로 옳지 않은 것은?',
    options: [
      'AS 키워드를 생략할 수 있다',
      '별칭에 공백이 있으면 따옴표로 감싸야 한다',
      '별칭은 WHERE 절에서 사용할 수 있다',
      '별칭은 ORDER BY 절에서 사용할 수 있다',
    ],
    answer: 3,
    explanation: 'SELECT 절의 별칭은 ORDER BY에서 사용 가능하지만, WHERE 절에서는 사용할 수 없습니다. WHERE은 SELECT보다 먼저 처리되기 때문입니다.',
  },
  {
    id: 246, category: '함수', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT MOD(10, 3) FROM DUAL;',
    options: ['3', '1', '0', '3.33'],
    answer: 2,
    explanation: 'MOD(피제수, 제수): 나머지를 반환합니다. 10 ÷ 3 = 3 나머지 1 → MOD(10, 3) = 1',
  },
  {
    id: 247, category: '함수', subject: '2과목', type: '변형', difficulty: '중',
    question: '다음 SQL의 결과로 옳은 것은?\n\nSELECT CEIL(4.1) FROM DUAL;',
    options: ['4', '5', '4.1', '4.2'],
    answer: 2,
    explanation: 'CEIL(숫자): 소수점 이하를 올림하여 정수 반환. CEIL(4.1) = 5. FLOOR(4.9) = 4(내림).',
  },
  {
    id: 248, category: 'JOIN', subject: '2과목', type: '변형', difficulty: '상',
    question: '다음 SQL에서 조인 결과의 행 수로 옳은 것은?\n\n-- A: 3행, B: 4행 (공통 키로 A 2행, B 3행 매칭)\nSELECT * FROM A\nFULL OUTER JOIN B ON A.ID = B.ID;',
    options: ['2', '3', '5', '12'],
    answer: 3,
    explanation: 'FULL OUTER JOIN: 매칭된 행(2행) + A에만 있는 행(1행) + B에만 있는 행(1행) = 4행. 단, 정확한 수는 데이터에 따라 다릅니다. 일반적으로 MAX(A행수, B행수) 이상.',
  },
  {
    id: 249, category: 'NULL처리', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 SQL에서 COL1이 NULL인 행을 제외하고 조회하는 올바른 방법은?',
    options: [
      'WHERE COL1 != NULL',
      'WHERE COL1 <> NULL',
      'WHERE COL1 IS NOT NULL',
      'WHERE COL1 NOT NULL',
    ],
    answer: 3,
    explanation: 'NULL 비교에는 반드시 IS NULL / IS NOT NULL을 사용해야 합니다. != NULL, <> NULL은 항상 UNKNOWN을 반환하여 행이 선택되지 않습니다.',
  },
  {
    id: 250, category: 'GROUP BY/HAVING', subject: '2과목', type: '기출', difficulty: '중',
    question: '다음 SQL의 실행 결과로 옳은 것은?\n\nSELECT DEPTNO, MAX(SAL)\nFROM EMP\nGROUP BY DEPTNO\nORDER BY 2 DESC;',
    options: [
      'DEPTNO별 최대 급여를 오름차순으로 정렬',
      'DEPTNO별 최대 급여를 내림차순으로 정렬',
      'DEPTNO를 내림차순으로 정렬',
      '오류가 발생한다',
    ],
    answer: 2,
    explanation: 'ORDER BY 2 DESC: SELECT 절의 두 번째 컬럼(MAX(SAL))을 기준으로 내림차순 정렬합니다. 숫자로 컬럼 순서를 지정할 수 있습니다.',
  },
];
